spring.application.name=UserLoginLogout

# Enable multipart upload
spring.servlet.multipart.enabled=true

# Max file size (single file)
spring.servlet.multipart.max-file-size=300MB

# Max request size (total request including all files)
spring.servlet.multipart.max-request-size=300MB

# File size threshold (after this size, file is written to disk instead of memory)
spring.servlet.multipart.file-size-threshold=2KB

spring.datasource.url=jdbc:mysql://localhost:3306/User_Logs?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



cloudinary.cloud-name=dnobccfnx
cloudinary.api-key=859246969353965


cloudinary.api-secret=XWO0Bue2kwYGspcJN0sM4kaMeT4
